title: 'Hi, it''s Yiwei'
baseURL: /
params:
  description: Yiwei's developer portfolio and blog
  color_scheme: light
  accent_color: pink
  header:
    type: header
    title: YIwei J.
    has_nav: true
    nav_links:
      - type: action
        label: Home
        url: /
        style: link
      - type: action
        label: Portfolio
        url: /portfolio/
        style: link
      - type: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        label: Contact
        url: /contact/
        style: link
  footer:
    type: footer
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created on <a
      href="https://www.stackbit.com" target="_blank"
      rel="noopener">Stackbit</a>. Get yours <a
      href="https://app.stackbit.com/create?theme=exto" target="_blank"
      rel="noopener">here</a>.
    has_social: true
    social_links:
      - type: action
        label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
      - label: Github
        url: lorem-ipsum
        style: icon
        icon_class: fa-github
        new_window: false
        type: action
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
